name: Build and Push Outputs to Demo Repo

on:
  pull_request:
    types:
      - opened
      - closed
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Reviewers
        id: reviewers
        run: |
          if [ "${{ github.event.pull_request.requested_reviewers }}" != "[]" ]; then
            echo "reviewers=$(echo ${{ github.event.pull_request.requested_reviewers }} | jq -r 'map(.login) | join(", ")')" >> $GITHUB_ENV
          else
            echo "reviewers=No reviewers assigned" >> $GITHUB_ENV
          fi

      - name: Post a message in a channel
        id: pr_message
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_TOKEN }}
          payload: |
            channel: C082SRACXL5
            attachments: [
              {
                "color": "${{ github.event.action == 'opened' && '#238636' || '#8957E5' }}",
                "blocks": [
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "${{ github.event.action == 'opened' && ':bell: *Pull Request Opened!*' || ':white_check_mark: *Pull Request Closed!*' }}"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Author:* ${{ github.event.pull_request.user.login }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Title:* ${{ github.event.pull_request.title }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*PR Number:* #${{ github.event.pull_request.number }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Link:* <${{ github.event.pull_request.html_url }}|View Pull Request>"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Reviewers:* ${{ env.reviewers }}"
                      }
                    ]
                  }
                ]
              }
            ]
