name: Build and Push Outputs to Demo Repo

on:
  pull_request:
    types:
      - opened
      - closed
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Post a message in a channel
        id: pr_message
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_TOKEN }}
          payload: |
            channel: C082SRACXL5
            attachments: [
              {
                "color": "${{ github.event.action == 'opened' && '#238636' || '#8957E5' }}",
                "blocks": [
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "${{ github.event.action == 'opened' && ':bell: *Pull Request Opened!*' || ':white_check_mark: *Pull Request Closed!*' }}"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Author:* ${{ github.event.pull_request.user.login }}"
                      },
                      {
                        "type": "context",
                        "elements": [
                          "type": "image",
                          "image_url": "${{ github.event.pull_request.user.avatar_url }}",
                          "alt_text": "image"
                        ],
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Title:* ${{ github.event.pull_request.title }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*PR Number:* #${{ github.event.pull_request.number }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Link:* <${{ github.event.pull_request.html_url }}|View Pull Request>"
                      }
                    ]
                  }
                ]
              }
            ]
