name: Build and Push Outputs to Demo Repo

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Post a message in a channel
        id: deployment_message
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_TOKEN }}
          payload: |
            channel: C082SRACXL5
            text: "building..."
      # Install dependencies (Modify this to your project)
      - name: Simulate process
        run: exit 0

      - name: Success message
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_TOKEN }}
          payload: |
            channel: C082SRACXL5
            thread_ts: "${{ steps.deployment_message.outputs.ts }}"
            text: "success..."
