name: Build and Push Outputs to Demo Repo

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Post a message in a channel
        id: deployment_message
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_TOKEN }}
          payload: |
            channel: C082SRACXL5
            text: "Deployment started :eyes:"
            attachments:
              - color: "#dbab09"
                fields:
                  - title: "Status"
                    short: true
                    value: In Progress
      # Install dependencies (Modify this to your project)
      - name: Simulate process
        run: |
          sleep 10
          exit 1

      - name: Success message
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.update
          token: ${{ secrets.SLACK_TOKEN }}
          payload: |
            channel: C082SRACXL5
            ts: "${{ steps.deployment_message.outputs.ts }}"
            attachments: [
              {
                "color": "#36a64f",
                "blocks": [
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Deployment finished!* :rocket:"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Commit:*\n<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.event.head_commit.message }}>"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Action:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{github.run_id}}>"
                      }
                    ]
                  }
                ]
              }
            ]
      - name: Fail message
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.update
          token: ${{ secrets.SLACK_TOKEN }}
          payload: |
            channel: C082SRACXL5
            ts: "${{ steps.deployment_message.outputs.ts }}"
            attachments: [
              {
                "color": "#f44336",
                "blocks": [
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Deployment Failed!* :red_circle:"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Commit:*\n<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.event.head_commit.message }}>"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Action:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{github.run_id}}>"
                      }
                    ]
                  }
                ]
              }
            ]

      # - name: after fail message
      #   if: ${{ failure() }}
      #   uses: slackapi/slack-github-action@v2.0.0
      #   with:
      #     method: chat.postMessage
      #     token: ${{ secrets.SLACK_TOKEN }}
      #     payload: |
      #       channel: C082SRACXL5
      #       thread_ts: "${{ steps.deployment_message.outputs.ts }}"
      #       text: "will not proceed to another build on ${{ github.sha }} and ${{ github.ref }}"
