name: Build and Push Outputs to Demo Repo

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Post a message in a channel
        id: deployment_message
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_TOKEN }}
          payload: |
            channel: C082SRACXL5
            attachments: [
              {
                "color": "#D29922",
                "blocks": [
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Building...* :building_construction:"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Action:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{github.run_id}}>"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*${{ github.event.head_commit.message }}*"
                    },
                    "accessory": {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Go to Commit",
                        "emoji": true
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}",
                      "action_id": "button-action"
                    }
                  },
                ]
              }
            ]
      # Install dependencies (Modify this to your project)
      - name: Simulate process
        run: |
          sleep 10
          exit 0

      - name: Notify Status
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.update
          token: ${{ secrets.SLACK_TOKEN }}
          payload: |
            channel: C082SRACXL5
            ts: "${{ steps.deployment_message.outputs.ts }}"
            attachments: [
              {
                "color": "${{ job.status == 'success' && '#238636' || '#F85149' }}",
                "blocks": [
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "${{ job.status == 'success' && '*Build finished!* :rocket:' || '*Build Failed!* :red_circle:' }}"
                        
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Action:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{github.run_id}}>"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*${{ github.event.head_commit.message }}*"
                    },
                    "accessory": {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Go to Commit",
                        "emoji": true
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}",
                      "action_id": "button-action"
                    }
                  },
                ]
              }
            ]
